### ISSUE TITLE
Dark Sky API

### ISSUE THREAD

**Issue by xthelavr** [Kuzmrom7/weather-spot#1]
I think [Dark Sky API](https://darksky.net/dev) is better, because
- that API returns icon for weather (you don't need additional dependencies)
- pretty format of data
- a lot of fields that contains information about weather
- a lot of languages

also I found a good [lib](https://github.com/deanbot/dark-sky-api) for this

**Comment by Kuzmrom7** [comment]
Oh, thank you for issue!
if I have time, I will rewrite  using Dark Sky API

**Comment by lavrxxx** [comment]
Do you find the time to replace weather api?

**Comment by kuzmrom7** [comment]
https://darksky.net/dev
